source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg"
gem "puma"
gem "bootsnap", require: false

gem "propshaft"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "devise"
gem "devise-two-factor"
gem "redis"
gem "redis-session-store"

group :development, :test do
  gem "debug"
  gem "brakeman", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end
